# @package scheduler
function:
  _target_: src.opts.FlatCos
  num_epochs: ${num_epochs}
  pct_start: 0.7
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: step # step or epoch
