# @package scheduler
function:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones:
    - 5
  gamma: 0.1
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: epoch # step or epoch

