training:
  seed: ${seed}
  job_name: ${run_name}
  checkpoint_path: ${checkpoint_path}
  model_save_dir: ${model_save_dir}
  num_epochs: 30 # totat number of epochs to train for
  total_steps: null # this is optional;
  lr: 0.01 # learning_rate
  num_classes: 5 # number of output classes
  image_dim: 224 # heght/width of the image after transformation
  metric: val_loss
  
  dataloaders:
    batch_size: 128
    pin_memory: true
    num_workers: 5
