defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentations: light-augs
  - datamodule: default
  - network: snapmix
  - mixmethod: snapmix
  - optimizer: adam
  - scheduler: cosine-warmup
  - loss: labelsmoothing
  - general: kaggle
  - trainer: default

encoder: tf_efficientnet_b3_ns
accumulate_batches: 1
clip_grad_norm: 0
image_dims: 512
num_epochs: 10
learning_rate: 1e-03
lr_mult: 10

hydra:
  run:
    dir: ${general.save_dir}
