defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light_augs_resnet50_512
  - trainer: default
  - networks: snapmix
  - mixmethods: snapmix
  - losses: labelsmoothing
  - activation: relu
  - optimizers: adamw
  - schedulers: 02-01-20-seresnext50_32x4d
  - general: kaggle

curr_fold: 0
image_dir: ${general.image_dir}
csv_path: ${general.csv_path}

encoder: seresnext50_32x4d

accumulate_batches: 1
clip_grad_norm: 0.5

image_dims: 512
num_epochs: 20
batch_size: 32

learning_rate: 0.1
lr_mult: 10
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: step # step or epoch
