defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light_augs_resnet50
  - trainer: default
  - networks: snapmix
  - mixmethods: snapmix
  - losses: crossentropy
  - activation: relu
  - optimizers: sgdnesterov
  - schedulers: multisteplr
  - general: kaggle

curr_fold: 0
image_dir: ${general.image_dir}
csv_path: ${general.csv_path}

encoder: resnet50
accumulate_batches: 1
clip_grad_norm: 0

image_dims: 480
num_epochs: 40
batch_size: 32

learning_rate: 0.01
lr_mult: 10
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: epoch # step or epoch
