defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light-augs-center-crop-512
  - networks: snapmix
  - mixmethods: snapmix-half-prob
  - optimizers: ranger
  - schedulers: flatcos
  - activation: relu
  - losses: labelsmoothing
  - general: kaggle
  - trainer: default

curr_fold: 0
image_dir: ${general.image_dir}
csv_path: ${general.csv_path}

encoder: tf_efficientnet_b3_ns

accumulate_batches: 1
clip_grad_norm: 0

image_dims: 512
num_epochs: 15
batch_size: 32

learning_rate: 0.1
lr_mult: 10
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: step # step or epoch
