defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light_augs_resnet50_512
  - networks: snapmix
  - mixmethods: snapmix
  - optimizers: sgd-nesterov
  - schedulers: sgdr
  - activation: relu
  - losses: labelsmoothing
  - general: kaggle
  - trainer: default

curr_fold: 0
image_dir: /kaggle/input/cassava-leaf-disease-classification/train_images/
csv_path: /kaggle/working/leaf-disease-classification-kaggle/data/stratified-data-5folds.csv

encoder: tf_efficientnet_b3_ns

accumulate_batches: 1
clip_grad_norm: 0

image_dims: 512
num_epochs: 15
batch_size: 32

learning_rate: 0.1
lr_mult: 10
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: epoch # step or epoch
