defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentations: light-augs
  - network: snapmix
  - mixmethod: snapmix
  - optimizer: ranger
  - scheduler: flatcos
  - activation: relu
  - loss: labelsmoothing
  - general: kaggle
  - trainer: default

curr_fold: 0
image_dir: ${general.image_dir}
csv_path: ${general.csv_path}

encoder: seresnext50_32x4d

accumulate_batches: 1
clip_grad_norm: 1.0

image_dims: 512
num_epochs: 10
batch_size: 32

learning_rate: 1e-03
lr_mult: 100

hydra:
  run:
    dir: ${general.save_dir}
