defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentations: light-augs
  - datamodule: default
  - network: seresnext101-snapmix
  - mixmethod: default
  - optimizer: adamw
  - scheduler: linear-warmup
  - activation: relu
  - loss: labelsmoothing
  - general: kaggle
  - trainer: default

encoder: vit_base_patch16_224
accumulate_batches: 1
clip_grad_norm: 0
image_dims: 224
num_epochs: 10
learning_rate: 1e-03
lr_mult: 10

hydra:
  run:
    dir: ${general.save_dir}
