defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light_augs
  - trainer: default

config:
  random_seed: 42
  project_name: kaggle-leaf-disease-hydra-cli

  unique_idx: null

  curr_fold: 0
  image_dir: /content/cassava-leaf-disease-classification/train_images
  csv_path: /content/leaf-disease-classification-kaggle/data/stratified-data-5folds.csv

  encoder: seresnext50_32x4d

  activation:
    _target_: torch.nn.ReLU
    inplace: true

  image_dims: 320
  num_epochs: 30
  batch_size: 32
  accumulate_batches: 1
  clip_grad_norm: 0.1

network:
  model:
    _target_: timm.create_model
    model_name: ${config.encoder}
    pretrained: True

  transfer_learning_model:
    _target_: src.networks.SnapMixTransferLearningModelBasic
    cut: -2
    c: 5

hparams:
  mixmethod:
    _target_: src.mixmethods.SnapMix
    alpha: 5.0
    conf_prob: 1.0

  loss_function:
    _target_: src.core.LabelSmoothingCrossEntropy
    eps: 0.1

  learning_rate: 0.003
  lr_mult: 100

  optimizer:
    _target_: torch.optim.Adam
    weight_decay: 0.0001
    betas: (.9, 0.99)
    eps: 1e-05

  scheduler:
    _target_: src.opts.CosineAnnealingWarmupScheduler
    warmup_epochs: 4
    total_epochs: ${config.num_epochs}

  metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
  step_after: epoch # step or epoch
  frequency: 1 # scheduler call frequency

save_dir: models/
