defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - augmentation: light_augs
  - trainer: default
  - networks: snapmix
  - losses: labelsmoothing
  - activation: relu
  - mixmethods: snapmix
  - optimizers: sgdnesterov
  - schedulers: multisteplr
  - general: default

curr_fold: 0
image_dir: /Users/ayushman/Desktop/Datasets/cassava/train_images/
csv_path: /Users/ayushman/Desktop/leaf-disease-classification-kaggle/data/stratified-data-5folds.csv

encoder: seresnext50_32x4d
accumulate_batches: 1
clip_grad_norm: 0.5

image_dims: 224
num_epochs: 40
batch_size: 64

learning_rate: 0.001
lr_mult: 100
metric_to_track: null # metric for ReduceLrOnPlateau Scheduler
scheduler_interval: epoch # step or epoch
