# @package general
project_name: kaggle-leaf-disease-hydra-cli
save_dir: results/
image_dir: /Users/ayushman/Desktop/Datasets/cassava/train_images/
csv_path: /Users/ayushman/Desktop/leaf-disease-classification-kaggle/data/stratified-data-5folds.csv
