# @package general
unique_idx: null # a unique id for the experiment if None, then generates one randomly
project_name: kaggle-leaf-disease-hydra-cli # wandb project name
random_seed: 42 # random seed for the expeiment
save_dir: models/ # where to save the trained model weights
