# @package training
unique_idx: null
random_seed: 42
fold: 0
encoder: tf_efficientnet_b3_ns
learning_rate: 8e-03
lr_mult: 100
num_epochs: 15
mix_epochs: null
batch_size: 32
accumulate_grad_batches: 1
patience: null
job_name: ${hydra:job.name}
