# @package training
unique_idx: null
random_seed: 42
fold: 0
encoder: tf_efficientnet_b3_ns
learning_rate: 8e-03
lr_mult: 10
num_epochs: 20
mix_epochs: 17
batch_size: 32
accumulate_grad_batches: 2
patience: 5
job_name: ${hydra:job.name}
