# @package network
model:
  _target_: pretrainedmodels.se_resnext101_32x4d
  pretrained: imagenet

transfer_learning_model:
  _target_: src.networks.TransferLearningModel
  cut: -2
  c: 5
  lin_ftrs: 512

activation: null
