# @package network
model:
  _target_: timm.create_model
  model_name: ${encoder}
  pretrained: True
  drop_rate: 0.25

transfer_learning_model:
  _target_: src.networks.TransferLearningModel
  cut: -2
  c: 5
  lin_ftrs: 512

activation: null
