# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"object_from_dict": "00_core.ipynb",
         "idx2lbl": "00_core.ipynb",
         "conf_mat_idx2lbl": "00_core.ipynb",
         "seed_everything": "00_core.ipynb",
         "generate_random_id": "00_core.ipynb",
         "load_dataset": "00_core.ipynb",
         "DummyDataset": "00_core.ipynb",
         "ImageClassificationFromDf": "00_core.ipynb",
         "LabelSmoothingCrossEntropy": "00_core.ipynb",
         "params": "00a_lightning.core.ipynb",
         "CassavaLightningDataModule": "00a_lightning.core.ipynb",
         "LightningCassava": "00a_lightning.core.ipynb",
         "AlbumentationsTransform": "00b_fastai.core.ipynb",
         "timm_learner": "00b_fastai.core.ipynb",
         "timm_splitter": "00b_fastai.core.ipynb",
         "NoneReduce": "01_mixmethods.ipynb",
         "Mixup": "01_mixmethods.ipynb",
         "Cutmix": "01_mixmethods.ipynb",
         "SnapMix": "01_mixmethods.ipynb",
         "WandbImageClassificationCallback": "01a_lightning.callbacks.ipynb",
         "LitProgressBar": "01a_lightning.callbacks.ipynb",
         "PrintLogsCallback": "01a_lightning.callbacks.ipynb",
         "norm_types": "02_layers.ipynb",
         "requires_grad": "02_layers.ipynb",
         "init_default": "02_layers.ipynb",
         "cond_init": "02_layers.ipynb",
         "apply_leaf": "02_layers.ipynb",
         "apply_init": "02_layers.ipynb",
         "AdaptiveConcatPool2d": "02_layers.ipynb",
         "Mish": "02_layers.ipynb",
         "cut_model": "02_layers.ipynb",
         "num_features_model": "02_layers.ipynb",
         "create_head": "02_layers.ipynb",
         "replace_activs": "02_layers.ipynb",
         "TransferLearningModel": "02a_networks.ipynb",
         "SnapMixTransferLearningModelBasic": "02a_networks.ipynb",
         "SnapMixTransferLearningModel": "02a_networks.ipynb",
         "Lookahead": "03_optimizers.ipynb",
         "RAdam": "03_optimizers.ipynb",
         "Ranger": "03_optimizers.ipynb",
         "FlatCos": "03_optimizers.ipynb",
         "GradualWarmupScheduler": "03_optimizers.ipynb",
         "CosineAnnealingWarmupScheduler": "03_optimizers.ipynb"}

modules = ["core.py",
           "lightning/core.py",
           "fast/core.py",
           "mixmethods.py",
           "lightning/callbacks.py",
           "layers.py",
           "networks.py",
           "opts.py"]

doc_url = "https://fastai.github.io/src/"

git_url = "https://github.com/fastai/src/tree/master/"

def custom_doc_links(name): return None
