# @package trainer
_target_: pytorch_lightning.Trainer
gpus: -1
precision: 16
max_epochs: ${num_epochs}
accumulate_grad_batches: ${training.accumulate_grad_batches}
gradient_clip_val: 0.5
log_every_n_steps: 1
num_sanity_val_steps: 0
weights_summary: null
deterministic: true
reload_dataloaders_every_epoch: true
automatic_optimization: true
