# @package trainer
_target_: pytorch_lightning.Trainer
gpus: -1
accumulate_grad_batches: ${config.accumulate_batches}
profiler: False
max_epochs: ${config.num_epochs}
log_every_n_steps: 1
num_sanity_val_steps: 0
gradient_clip_val: ${config.clip_grad_norm}
weights_summary: null
deterministic: true
precision: 16
